# 사이트 기본 설정
title: MuCaRD Challenge
description: Multi-Camera Robust Diagnosis of Fundus Diseases
baseurl: ""        # 프로젝트 사이트: 예) "/MICCAI2025MuCARD"
url: "https://hyeonminkim0625.github.io"
theme: ""          # 커스텀 레이아웃 사용하므로 빈 값
markdown: kramdown